<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChessSharp\ChessSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Images\logo-chesssharp.png" />
    <None Remove="Assets\Images\Pieces\*.png" />

    <Resource Include="Assets\Images\logo-chesssharp.png" />
    <Resource Include="Assets\Images\Pieces\*.png" />
  </ItemGroup>

</Project>