<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChessSharp\ChessSharp.csproj" />
  </ItemGroup>

<ItemGroup>
  <Resource Include="Assets\Images\background-marble.png" />
  <Resource Include="Assets\Images\board-premium.png" />
  <Resource Include="Assets\Images\logo-chesssharp.png" />
  <Resource Include="Assets\Images\Pieces\*.png" />
</ItemGroup>

</Project>