<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="AI\**\*.cs" />
    <Compile Remove="Board\**\*.cs" />
    <Compile Remove="Enums\**\*.cs" />
    <Compile Remove="Game\**\*.cs" />
    <Compile Remove="Pieces\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ChessSharp.Core\ChessSharp.Core.csproj" />
  </ItemGroup>

</Project>
